### ISSUE TITLE
Exception when running wizard on macOS

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-wizard#80] opened 2019-11-26 14:10 UTC
The wizard throws some internal error:

```
/Users/paul/Downloads/raiden_wizard ; exit;
[81117] PyInstaller Bootloader 3.x
[81117] LOADER: executable is /Users/paul/Downloads/raiden_wizard
[81117] LOADER: homepath is /Users/paul/Downloads
[81117] LOADER: _MEIPASS2 is NULL
[81117] LOADER: archivename is /Users/paul/Downloads/raiden_wizard
[81117] LOADER: Extracting binaries
[81117] LOADER: Executing self as child
[81117] LOADER: set _MEIPASS2 to /var/folders/g4/rq2cz9m969x4zy_9x04bdv9r0000gn/T/_MEIHbLVHa
[81117] LOADER: Registering signal handlers
[81118] PyInstaller Bootloader 3.x
[81118] LOADER: executable is /Users/paul/Downloads/raiden_wizard
[81118] LOADER: homepath is /Users/paul/Downloads
[81118] LOADER: _MEIPASS2 is /var/folders/g4/rq2cz9m969x4zy_9x04bdv9r0000gn/T/_MEIHbLVHa
[81118] LOADER: archivename is /Users/paul/Downloads/raiden_wizard
[81118] LOADER: Already in the child - running user's code.
[81118] LOADER: Python library: /var/folders/g4/rq2cz9m969x4zy_9x04bdv9r0000gn/T/_MEIHbLVHa/Python
[81118] LOADER: Loaded functions from Python library.
[81118] LOADER: Manipulating environment (sys.path, sys.prefix)
[81118] LOADER: sys.prefix is /var/folders/g4/rq2cz9m969x4zy_9x04bdv9r0000gn/T/_MEIHbLVHa
[81118] LOADER: Pre-init sys.path is /var/folders/g4/rq2cz9m969x4zy_9x04bdv9r0000gn/T/_MEIHbLVHa/base_library.zip:/var/folders/g4/rq2cz9m969x4zy_9x04bdv9r0000gn/T/_MEIHbLVHa
[81118] LOADER: Setting runtime options
[81118] LOADER: Initializing python
[81118] LOADER: Overriding Python's sys.path
[81118] LOADER: Post-init sys.path is /var/folders/g4/rq2cz9m969x4zy_9x04bdv9r0000gn/T/_MEIHbLVHa/base_library.zip:/var/folders/g4/rq2cz9m969x4zy_9x04bdv9r0000gn/T/_MEIHbLVHa
[81118] LOADER: Setting sys.argv
[81118] LOADER: setting sys._MEIPASS
[81118] LOADER: importing modules from CArchive
[81118] LOADER: extracted struct
[81118] LOADER: callfunction returned...
[81118] LOADER: extracted pyimod01_os_path
[81118] LOADER: callfunction returned...
[81118] LOADER: extracted pyimod02_archive
[81118] LOADER: callfunction returned...
[81118] LOADER: extracted pyimod03_importers
[81118] LOADER: callfunction returned...
[81118] LOADER: Installing PYZ archive with Python modules.
[81118] LOADER: PYZ archive: PYZ-00.pyz
[81118] LOADER: Running pyiboot01_bootstrap.py
[81118] LOADER: Running runtime_raiden_contracts.py
[81118] LOADER: Running pyi_rth_pkgres.py
[81118] LOADER: Running pyi_rth_multiprocessing.py
[81118] LOADER: Running pyi_rth_certifi.py
[81118] LOADER: Running web.py
2019-11-26 15:06.17 Starting web server
WARNING:tornado.access:404 GET /favicon.ico (::1) 0.70ms
2019-11-26 15:07.40 Generating new wallet and configuration file for raiden
2019-11-26 15:07.43 Obtaining Goerli ETH through faucet
2019-11-26 15:07.53 Balance is 0.1 ETH
2019-11-26 15:07.53 Account funded with 0.1 ETH
2019-11-26 15:07.53 Minting RDN
2019-11-26 15:07.53 Estimated cost: 0.002 ETH
ERROR:tornado.application:Uncaught exception GET /ws (::1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/ws', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "tornado/websocket.py", line 649, in _run_callback
  File "raiden_installer/web.py", line 126, in on_message
  File "raiden_installer/web.py", line 182, in _run_setup
  File "raiden_installer/web.py", line 150, in _run_funding
  File "raiden_installer/transactions.py", line 44, in mint_tokens
  File "raiden_installer/utils.py", line 51, in send_raw_transaction
  File "web3/eth.py", line 275, in sendRawTransaction
  File "web3/manager.py", line 112, in request_blocking
ValueError: {'code': -32000, 'message': 'insufficient funds for gas * price + value'}
```

System info:
`Darwin pauls-mbp-2.intern 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64`

**Comment by manuelwedler** [comment] 2020-09-24 12:23
This might have happened because we didn't wait for some blocks for the new balance to be confirmed. 
We wait now for 5 blocks before we send this transaction, so this should not happen anymore. Besides the new tests don't run into this issue. So I am closing.

**Closed by manuelwedler** 2020-09-24 12:23 UTC
